export const news: SiteList = [
    { name: 'Urk.net', link: 'https://www.ukr.net/ua/' },
    { name: 'BBC News Україна', link: 'https://www.bbc.com/ukrainian' },
    { name: 'Українська правда', link: ' https://www.pravda.com.ua/' },
    { name: 'Unian', link: 'https://www.unian.ua/' },
    { name: 'Українські новини', link: 'https://ukranews.com/ua' },
    { name: 'Кореспондент', link: 'https://ua.korrespondent.net/' },
    { name: 'Голос Америки', link: 'https://ukrainian.voanews.com/' },
    { name: 'ТСН', link: 'https://tsn.ua/' },
    { name: 'New Voice (НВ)', link: 'https://nv.ua/' },
    { name: 'Главком', link: 'https://glavcom.ua/' },
    { name: 'Цензор.НЕТ', link: 'https://censor.net/' },
    { name: 'UNN', link: 'https://www.unn.com.ua/' },
    { name: 'Gazeta.ua', link: 'https://gazeta.ua/' },
    { name: 'Obozrevatel', link: 'https://www.obozrevatel.com/' },
    { name: 'Еспресо', link: 'https://espreso.tv/' },
    { name: 'Укрінформ', link: 'https://www.ukrinform.ua/' },
    { name: '5 телеканал', link: 'https://www.5.ua/' },
    { name: 'Бабель', link: 'https://babel.ua/' },
    { name: 'Громадське телебачення', link: 'https://hromadske.ua/' },
    { name: 'ЛІГА.Новини', link: 'https://news.liga.net/' },
    { name: 'Факти', link: 'https://fakty.com.ua/ua/' },
    { name: 'Гордон', link: 'https://gordonua.com/' },
    { name: '24 телеканал', link: 'https://24tv.ua/' },
    { name: 'Радіо Свобода', link: 'https://www.radiosvoboda.org/' },
    { name: 'ZAZID.NET', link: 'https://zaxid.net/' },
    { name: 'META', link: 'https://meta.ua/uk/' },
    { name: 'Мілітарний', link: 'https://mil.in.ua/uk/' },
    { name: 'Накипіло', link: 'https://nakipelo.ua/' },
    { name: 'Новинарня', link: 'https://novynarnia.com/' },
    { name: 'ҐРУНТ', link: 'https://grnt.media/' },
    { name: 'Слово і Діло', link: 'https://www.slovoidilo.ua/' },
    { name: 'Mezha', link: 'https://mezha.media/' },
];
